name: macOS type diagnostics

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: grep sys/types.h
        run: fgrep int32_t /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/types.h

      - name: cat sys/types.h
        run: cat /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/types.h
